# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import autocomp_pb2 as autocomp__pb2


class AutoCompleteStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchNext = channel.unary_unary(
                '/autocomplete.AutoComplete/FetchNext',
                request_serializer=autocomp__pb2.InferenceRequest.SerializeToString,
                response_deserializer=autocomp__pb2.InferenceResponse.FromString,
                )


class AutoCompleteServicer(object):
    """The service definition.
    """

    def FetchNext(self, request, context):
        """Sends a request and gets a response from the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutoCompleteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchNext': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchNext,
                    request_deserializer=autocomp__pb2.InferenceRequest.FromString,
                    response_serializer=autocomp__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autocomplete.AutoComplete', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AutoComplete(object):
    """The service definition.
    """

    @staticmethod
    def FetchNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/autocomplete.AutoComplete/FetchNext',
            autocomp__pb2.InferenceRequest.SerializeToString,
            autocomp__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
