// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: autocomp.proto
#ifndef GRPC_autocomp_2eproto__INCLUDED
#define GRPC_autocomp_2eproto__INCLUDED

#include "autocomp.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace autocomplete {

// The service definition.
class AutoComplete final {
 public:
  static constexpr char const* service_full_name() {
    return "autocomplete.AutoComplete";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a request and gets a response from the server.
    virtual ::grpc::Status FetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::autocomplete::InferenceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::autocomplete::InferenceResponse>> AsyncFetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::autocomplete::InferenceResponse>>(AsyncFetchNextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::autocomplete::InferenceResponse>> PrepareAsyncFetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::autocomplete::InferenceResponse>>(PrepareAsyncFetchNextRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a request and gets a response from the server.
      virtual void FetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest* request, ::autocomplete::InferenceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest* request, ::autocomplete::InferenceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::autocomplete::InferenceResponse>* AsyncFetchNextRaw(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::autocomplete::InferenceResponse>* PrepareAsyncFetchNextRaw(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status FetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::autocomplete::InferenceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::autocomplete::InferenceResponse>> AsyncFetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::autocomplete::InferenceResponse>>(AsyncFetchNextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::autocomplete::InferenceResponse>> PrepareAsyncFetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::autocomplete::InferenceResponse>>(PrepareAsyncFetchNextRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void FetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest* request, ::autocomplete::InferenceResponse* response, std::function<void(::grpc::Status)>) override;
      void FetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest* request, ::autocomplete::InferenceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::autocomplete::InferenceResponse>* AsyncFetchNextRaw(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::autocomplete::InferenceResponse>* PrepareAsyncFetchNextRaw(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FetchNext_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a request and gets a response from the server.
    virtual ::grpc::Status FetchNext(::grpc::ServerContext* context, const ::autocomplete::InferenceRequest* request, ::autocomplete::InferenceResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchNext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FetchNext() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FetchNext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchNext(::grpc::ServerContext* /*context*/, const ::autocomplete::InferenceRequest* /*request*/, ::autocomplete::InferenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchNext(::grpc::ServerContext* context, ::autocomplete::InferenceRequest* request, ::grpc::ServerAsyncResponseWriter< ::autocomplete::InferenceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FetchNext<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_FetchNext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FetchNext() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::autocomplete::InferenceRequest, ::autocomplete::InferenceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::autocomplete::InferenceRequest* request, ::autocomplete::InferenceResponse* response) { return this->FetchNext(context, request, response); }));}
    void SetMessageAllocatorFor_FetchNext(
        ::grpc::MessageAllocator< ::autocomplete::InferenceRequest, ::autocomplete::InferenceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::autocomplete::InferenceRequest, ::autocomplete::InferenceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FetchNext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchNext(::grpc::ServerContext* /*context*/, const ::autocomplete::InferenceRequest* /*request*/, ::autocomplete::InferenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FetchNext(
      ::grpc::CallbackServerContext* /*context*/, const ::autocomplete::InferenceRequest* /*request*/, ::autocomplete::InferenceResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_FetchNext<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FetchNext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FetchNext() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FetchNext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchNext(::grpc::ServerContext* /*context*/, const ::autocomplete::InferenceRequest* /*request*/, ::autocomplete::InferenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FetchNext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FetchNext() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FetchNext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchNext(::grpc::ServerContext* /*context*/, const ::autocomplete::InferenceRequest* /*request*/, ::autocomplete::InferenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchNext(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FetchNext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FetchNext() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FetchNext(context, request, response); }));
    }
    ~WithRawCallbackMethod_FetchNext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchNext(::grpc::ServerContext* /*context*/, const ::autocomplete::InferenceRequest* /*request*/, ::autocomplete::InferenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FetchNext(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FetchNext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FetchNext() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::autocomplete::InferenceRequest, ::autocomplete::InferenceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::autocomplete::InferenceRequest, ::autocomplete::InferenceResponse>* streamer) {
                       return this->StreamedFetchNext(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FetchNext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FetchNext(::grpc::ServerContext* /*context*/, const ::autocomplete::InferenceRequest* /*request*/, ::autocomplete::InferenceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFetchNext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::autocomplete::InferenceRequest,::autocomplete::InferenceResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FetchNext<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_FetchNext<Service > StreamedService;
};

}  // namespace autocomplete


#endif  // GRPC_autocomp_2eproto__INCLUDED
