// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: autocomp.proto

#include "autocomp.pb.h"
#include "autocomp.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace autocomplete {

static const char* AutoComplete_method_names[] = {
  "/autocomplete.AutoComplete/FetchNext",
};

std::unique_ptr< AutoComplete::Stub> AutoComplete::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AutoComplete::Stub> stub(new AutoComplete::Stub(channel, options));
  return stub;
}

AutoComplete::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_FetchNext_(AutoComplete_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AutoComplete::Stub::FetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::autocomplete::InferenceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::autocomplete::InferenceRequest, ::autocomplete::InferenceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FetchNext_, context, request, response);
}

void AutoComplete::Stub::async::FetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest* request, ::autocomplete::InferenceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::autocomplete::InferenceRequest, ::autocomplete::InferenceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchNext_, context, request, response, std::move(f));
}

void AutoComplete::Stub::async::FetchNext(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest* request, ::autocomplete::InferenceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FetchNext_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::autocomplete::InferenceResponse>* AutoComplete::Stub::PrepareAsyncFetchNextRaw(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::autocomplete::InferenceResponse, ::autocomplete::InferenceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FetchNext_, context, request);
}

::grpc::ClientAsyncResponseReader< ::autocomplete::InferenceResponse>* AutoComplete::Stub::AsyncFetchNextRaw(::grpc::ClientContext* context, const ::autocomplete::InferenceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFetchNextRaw(context, request, cq);
  result->StartCall();
  return result;
}

AutoComplete::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AutoComplete_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AutoComplete::Service, ::autocomplete::InferenceRequest, ::autocomplete::InferenceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AutoComplete::Service* service,
             ::grpc::ServerContext* ctx,
             const ::autocomplete::InferenceRequest* req,
             ::autocomplete::InferenceResponse* resp) {
               return service->FetchNext(ctx, req, resp);
             }, this)));
}

AutoComplete::Service::~Service() {
}

::grpc::Status AutoComplete::Service::FetchNext(::grpc::ServerContext* context, const ::autocomplete::InferenceRequest* request, ::autocomplete::InferenceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace autocomplete

